baseURL = "https://www.crislei.dev"
languageCode = "en-us"
title = "Crislei Dev"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Crislei Terassi - All rights reserved"
enableEmoji = true
publishDir = "public"
googleAnalytics = "UA-1XXXXXXX1-X"
  
[params.author]
  name = "Crislei Terassi"
  thumbnail = "/images/author.jpg"
  description = "Creator of this site."

[params.index]
  picture = "/images/author.jpg"
  title = "Crislei Terassi"
  subtitle = "Hi!, I'm a software developer. Sharing some interesting stuff here!"
  mdtext = '''This is my personal website, showing the projects I'm working on.\
**Feel free to test the live demos and download the source on our GitHub.**
### Social'''
  alertbar = true

[params.social]
  github = "crtsms"
  linkedin = "crisleiterassi"
  twitter = "crtsms"

## Main Menu
[[menu.main]]
    name = "Projects"
    weight = 100
    identifier = "projects"
    url = "/tags/projects"
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"    
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"